version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Message broker
      - "15672:15672" # Management UI
    networks:
      - app-network

  orders-service:
    build: ./orders-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  orders-consumer-service:
    build: ./orders-consumer-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
